### PR TITLE
Fixed deadlock on Error

### PR DESCRIPTION
**Pull request by nur1popcorn**
This patch fixes the deadlock issue referenced in #32

### CODE REVIEW

**Comment by jelmerk** [comment]
Thanks for the PR!  I think that mostly makes sense. 

The one thing I  don't like about this, is that we would silently swallow checked exceptions and errors.

How about wrapping the exception in a custom runtime exception that extends from com.github.jelmerk.knn.hnsw.IndexException  and throwing that instead ?

**Comment by nur1popcorn** [comment]
Alright I implemented your suggestions tell me if you like the name of the exception.

**Comment by jelmerk** [comment]
how about UncategorizedIndexException instead

**Comment by nur1popcorn** [comment]
Ok do you think there is anything else that needs to be changed or is it ready to be merged into the master branch ?

**Comment by jelmerk** [comment]
nope, all good. thanks for the contribution!

**Pull request merged**
